cache:
  directories:
  - node_modules
language: node_js
node_js:
- '4'
- '6'
- '8'
- '9'
sudo: false
deploy:
  - provider: npm
    email: slobak@gmail.com
    skip_cleanup: true
    api_key:
      secure: ahwA9BC1ZWka/XABCDmaaetk1inNE6FnjndDL8PWQUEUFdai37pAr31n0/y0lSAcghnBrRQkekyHOZ0ddqBSoI0DRtqrP2B2nkZo/4eC/7q7y2QRl53yb/tvjvsI14fn5aSkyfdywMU5qOjOHpPDF5nk1scNpIDu3QlAuTWlN6o=
    on:
      tags: true
      node: '8'
      repo: Asana/node-asana
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: "PXQ4an+jGX2FW3ufsLl0F6auyFr6TbwM/QgyBcuhijTqQLB+vtV13yvCU4OgBmtpGjctIfHIt/BloRlkRocaq4D27bHRNiFc76k9LxyIkDWEvPmogkN42YRcmr7cBB1VFYEFmEi9lrk2m5Cpl6tfMaU2LVBLsUMNrI7YHkrMp4A="
    file:
      - dist/asana.js
      - dist/asana-min.js
    on:
      tags: true
      node: '8'
      repo: Asana/node-asana
after_deploy:
- git config --global user.email "git@asana.com"
- git config --global user.name "Asana"
env:
  global:
    secure: JGg/anMqdy4Jhk+HYSM+rTdTMi1i0HKu10sn7NoKWKtqinSSEb4q5sJP19RWz/ng/sYYK5SwYY3DYRPFkVxfopVedr0Uz3by9NojNHOEr8FKN+YQMRcvqa94p9RB4SuiF8Fp405vXW4JlhBlx/YxQHcs+BKjDQT88xM8TS0iqGM=
